import { Button, ScrollView, LineEdit } from "std-widgets.slint";
import { Item, ItemKey } from "./items.slint";
import { LazyList } from "./lazylist.slint";
import { Search, SearchState } from "./search.slint";


export component Explorer inherits Window {
    forward-focus: scope;

    in property <[Item]> items;
    in property <[string]> cwd: ["aaa", "bbb", "ccc"];
    in property <int> remaining: 0;
    property <SearchState> state: browsing;

    // Properly reset focus to the root scope on search exit
    changed state => {
        if state != SearchState.searching {
            scope.focus();
        }
    }

    callback open(key: ItemKey);
    callback navigate(count: int); // navigate to the i-th cwd component
    callback refresh-entries(offset: int, limit: int);
    callback search(text: string);

    // Reset scroll (call this after navigating)
    public function reset-scroll() {
        lazy.reset-scroll();
    }

    scope := FocusScope {
        KeyBinding {
            keys: @keys(Slash);
            activated => {
                if state != SearchState.searching {
                    state = SearchState.searching;
                }
            };
        }

        KeyBinding {
            keys: @keys(Escape);
            activated => {
                if state == SearchState.searching {
                    state = SearchState.inspecting;
                } else if state == SearchState.inspecting {
                    state = SearchState.browsing;
                    search("");
                } else if state == SearchState.browsing {
                   // TODO: reset selection
                }
            }
        }

        VerticalLayout {
            if state == SearchState.browsing: ScrollView {
                height: 50px;
                HorizontalLayout {
                    for item[index] in cwd: Button {
                        text: item;
                        clicked => navigate(index);
                    }
                }
            }

            if state != SearchState.browsing: Search {
                search(text) => {
                    search(text);
                    reset-scroll();
                }
                state <=> root.state;
            }

            lazy := LazyList {
                items: items;
                remaining: remaining;
                refresh-entries(offset, limit) => refresh-entries(offset, limit);
                open(key) => open(key);
            }
        }
    }
}
