import { Button, ScrollView } from "std-widgets.slint";
import { Item } from "./items.slint";
import { LazyList } from "./lazylist.slint";


export component Explorer inherits Window {
    in property <[Item]> items;
    in property <[string]> cwd: ["aaa", "bbb", "ccc"];
    in property <int> remaining: 0;

    callback open(id: int);
    callback navigate(count: int); // navigate to the i-th cwd component
    callback refresh(offset: int, limit: int);

    VerticalLayout {

        ScrollView {
            height: 50px;
            HorizontalLayout {
                for item[index] in cwd: Button {
                    text: item;
                    clicked => navigate(index);
                }
            }
        }

        LazyList {
            items: items;
            remaining: remaining;
            refresh(offset, limit) => refresh(offset, limit);
            open(id) => open(id);
        }
    }
}
