import { Config } from "config.slint";
import { Callbacks } from "./callbacks.slint";
import { ItemKey } from "./utils.slint";
import { Mouse } from "mouse.slint";

export struct Item {
    key: ItemKey,
    name: string,
    selected: bool,
    icon: image,
}

// Item slice with metadata for granular display changes
// without jittering (items & offset are not being updated independently)
export struct Items {
    items: [Item],
    remaining: int,
    offset: int,
}


export component ItemView inherits Rectangle {
    in property <length> list-y;
    in property <Item> item;
    in property <bool> has-cursor: false;

    background: ta.has-hover ? red : item.selected ? grey : transparent;
    border-width: has-cursor ? 2px : 0px;
    border-color: white;

    height: Config.item-height;
    border-radius: 15px;

    property <bool> ctrl: false;
    property <bool> shift: false;

    ta := TouchArea {

        // Use pointer event to keep track of modifiers.
        pointer-event(event) => {
            ctrl = event.modifiers.control;
            shift = event.modifiers.shift;

            if event.kind == PointerEventKind.down {
                Mouse.dragged = item.icon;
            }
            Mouse.pointer-event(event, ta.mouse-x, ta.mouse-y + list-y, true);
        }

        clicked => Callbacks.select(item.key, !ctrl);
        double-clicked => Callbacks.open(item.key);
    }

    HorizontalLayout {
        spacing: 10px;
        VerticalLayout {
            alignment: center;

            Image {
                source: item.icon;
                height: 50px;
                width: 50px;
            }
        }

        Text {
            text: item.name;
            vertical-alignment: center;
        }
    }
}
