/// Item key u64 workaround
export struct ItemKey {
    upper: int,
    lower: int,
}

export struct Item {
    key: ItemKey,
    name: string,
    selected: bool,
    icon: image,
}

export component ItemView inherits Rectangle {
    in property <Item> item;
    callback open(key: ItemKey);

    background: ta.has-hover ? red : item.selected ? grey : transparent;

    height: 100px;
    border-radius: 15px;

    ta := TouchArea {
        clicked => open(item.key);
    }

    HorizontalLayout {
        spacing: 10px;
        VerticalLayout {
            alignment: center;

            Image {
                source: item.icon;
                height: 50px;
                width: 50px;
            }
        }

        Text {
            text: item.name;
            vertical-alignment: center;
        }
    }
}
