import { Config } from "config.slint";
import { Callbacks } from "./callbacks.slint";
import { ItemKey } from "./utils.slint";


export struct Item {
    key: ItemKey,
    name: string,
    selected: bool,
    icon: image,
}

export component ItemView inherits Rectangle {
    in property <Item> item;
    in property <bool> has-cursor: false;

    background: ta.has-hover ? red : item.selected ? grey : transparent;
    border-width: has-cursor ? 2px : 0px;
    border-color: white;

    height: Config.item-height;
    border-radius: 15px;

    property <bool> ctrl: false;
    property <bool> shift: false;

    ta := TouchArea {

        // Use pointer event to keep track of modifiers.
        pointer-event(event) => {
            ctrl = event.modifiers.control;
            shift = event.modifiers.shift;
        }

        clicked => Callbacks.select(item.key, !ctrl);
        double-clicked => Callbacks.open(item.key);
    }

    HorizontalLayout {
        spacing: 10px;
        VerticalLayout {
            alignment: center;

            Image {
                source: item.icon;
                height: 50px;
                width: 50px;
            }
        }

        Text {
            text: item.name;
            vertical-alignment: center;
        }
    }
}
