import { Item, ItemView } from "./items.slint";
import { Range, Utils } from "./utils.slint";
import { ScrollView } from "std-widgets.slint";
import { Config } from "config.slint";
import { Callbacks } from "./callbacks.slint";


export component LazyList {
    in property <[Item]> items;
    in property <int> remaining: 0; // remaining entries to be padded with placeholders for accurate scrollbar size

    property <int> offset: Math.floor(-scroll.viewport-y / Config.item-total-height); // entries hidden by the current scroll offset
    property <int> limit: Math.ceil(scroll.visible-height / Config.item-total-height) + 1; // amount of visible entries
    property <{ x: length, y: length}> anchor;
    property <{ x: length, y: length}> cursor;
    property <bool> selecting: false;
    property <length> list-padding-top;

    // Refresh both entries and top padding rectangle at the same time
    // in order to avoid flickering when scrolling at high speed
    function refresh() {
        Callbacks.refresh-entries(offset, limit);
        list-padding-top = offset * Config.item-total-height;
    }

    changed offset => refresh();
    changed limit => refresh();

    // Reset scroll (call this after navigating)
    public function reset-scroll() {
        scroll.viewport-y = 0;
    }

    // Scroll on select when the cursor is near the top / bottom
    timer := Timer {
        interval: Config.scroll-tick;
        running: selecting;
        triggered() => {
            let range = Config.scroll-range;
            let top = scroll.y - scroll.viewport-y + range;
            let bottom = scroll.y + scroll.visible-height - scroll.viewport-y - range;

            // Check proximity to bottom
            if cursor.y > bottom {
                let speed = min((cursor.y - bottom) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                let clamped = min(delta, scroll.viewport-height - scroll.visible-height + scroll.viewport-y);
                cursor.y += clamped;
                scroll.viewport-y -= clamped;
            // Check proximity to top
            } else if cursor.y < top {
                let speed = min((top - cursor.y) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                let clamped = min(delta, -scroll.viewport-y);
                cursor.y -= clamped;
                scroll.viewport-y += clamped;
            }
        }
    }

    scroll := ScrollView {
        ta := TouchArea {
            pointer-event(event) => {
                if event.kind == PointerEventKind.down {
                    selecting = true;
                    anchor = { x: ta.mouse-x, y: ta.mouse-y };
                    cursor = anchor;
                    Callbacks.select-all(false); // clear selection
                } else if event.kind == PointerEventKind.up {
                    selecting = false;
                } else if event.kind == PointerEventKind.move && selecting {
                    let previous-range = Utils.selection-range(anchor.y, cursor.y);
                    let current-range = Utils.selection-range(anchor.y, ta.mouse-y);
                    let updates = Utils.selection-updates(previous-range, current-range);
                    Callbacks.select-update(updates);
                    cursor = { x: ta.mouse-x, y: ta.mouse-y };
                }
            }
        }

        VerticalLayout {
            spacing: Config.spacing;

            // Virtual padding for elements scrolled out of view
            Rectangle {
                height: list-padding-top;
            }

            for item[index] in items: ItemView {
                item: item;
            }

            // Virtual padding for remaining elements not yet scrolled into view
            Rectangle {
                height: remaining * Config.item-total-height;
            }
        }

        // Selection rectangle
        Rectangle {
            visible: selecting;

            border-color: green;
            border-width: 2px;
            border-radius: 5px;

            x: Math.min(anchor.x, cursor.x);
            y: Math.min(anchor.y, cursor.y);

            width: Math.abs(cursor.x - anchor.x);
            height: Math.abs(cursor.y - anchor.y);
        }
    }
}
