import { Item, ItemView } from "./items.slint";
import { Range, Utils } from "./utils.slint";
import { ScrollView } from "std-widgets.slint";
import { Config } from "config.slint";
import { Callbacks } from "./callbacks.slint";


export component LazyList {
    in property <[Item]> items;
    in property <int> remaining: 0; // remaining entries to be padded with placeholders for accurate scrollbar size
    property <int> cursor: -1;

    public function enter() {
        if cursor != -1 {
            let item = items[cursor - offset];
            Callbacks.open(item.key);
        }
    }

    // Set the cursor to the topmost visible element,
    // and fully scroll it into view.
    public function set-cursor() {
        cursor = offset;
        scroll.viewport-y = -cursor * Config.item-total-height;
    }

    public function up(select: bool) {
        if cursor == -1 {
            set-cursor();
        } else if cursor > 0 {
            cursor -= 1;
            let delta = -cursor * Config.item-total-height - scroll.viewport-y;
            if delta > 0 {
                scroll.viewport-y = -cursor * Config.item-total-height;
            }
        }
    }

    public function down(select: bool) {
        if cursor == -1 {
            set-cursor();
        } else if cursor < offset + items.length + remaining - 1 {
            cursor += 1;
            let delta = -cursor * Config.item-total-height - scroll.viewport-y + scroll.visible-height - Config.item-total-height;
            if delta < 0 {
                scroll.viewport-y = -cursor * Config.item-total-height + scroll.visible-height - Config.item-total-height;
            }
        }
    }

    property <int> offset: Math.floor(-scroll.viewport-y / Config.item-total-height); // entries hidden by the current scroll offset
    property <int> limit: Math.ceil(scroll.visible-height / Config.item-total-height) + 1; // amount of visible entries
    property <{ x: length, y: length}> anchor;
    property <{ x: length, y: length}> mouse;
    property <bool> selecting: false;
    property <length> list-padding-top;

    // Refresh both entries and top padding rectangle at the same time
    // in order to avoid flickering when scrolling at high speed
    function refresh() {
        Callbacks.refresh-entries(offset, limit);
        list-padding-top = offset * Config.item-total-height;
    }

    changed offset => refresh();
    changed limit => refresh();

    // Reset scroll (call this after navigating)
    public function reset-scroll() {
        scroll.viewport-y = 0;
    }

    // Scroll on select when the cursor is near the top / bottom
    timer := Timer {
        interval: Config.scroll-tick;
        running: selecting;
        triggered() => {
            let range = Config.scroll-range;
            let top = scroll.y - scroll.viewport-y + range;
            let bottom = scroll.y + scroll.visible-height - scroll.viewport-y - range;

            // Check proximity to bottom
            if mouse.y > bottom {
                let speed = min((mouse.y - bottom) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                let clamped = min(delta, scroll.viewport-height - scroll.visible-height + scroll.viewport-y);

                // Update selection
                let updates = Utils.selection-updates-from-pos(anchor.y, mouse.y, mouse.y + clamped);
                Callbacks.select-update(updates);

                mouse.y += clamped;
                scroll.viewport-y -= clamped;
            // Check proximity to top
            } else if mouse.y < top {
                let speed = min((top - mouse.y) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                let clamped = min(delta, -scroll.viewport-y);

                // Update selection
                let updates = Utils.selection-updates-from-pos(anchor.y, mouse.y, mouse.y - clamped);
                Callbacks.select-update(updates);

                mouse.y -= clamped;
                scroll.viewport-y += clamped;
            }
        }
    }

    scroll := ScrollView {
        animate viewport-y { duration: 50ms; }

        scrolled => {
            cursor = -1;
        }

        ta := TouchArea {
            pointer-event(event) => {
                if event.kind == PointerEventKind.down {
                    selecting = true;
                    anchor = { x: ta.mouse-x, y: ta.mouse-y };
                    mouse = anchor;
                    Callbacks.select-all(false); // clear selection
                } else if event.kind == PointerEventKind.up {
                    selecting = false;
                } else if event.kind == PointerEventKind.move && selecting {
                    let updates = Utils.selection-updates-from-pos(anchor.y, mouse.y, ta.mouse-y);
                    Callbacks.select-update(updates);
                    mouse = { x: ta.mouse-x, y: ta.mouse-y };
                }
            }
        }

        VerticalLayout {
            spacing: Config.spacing;

            // Virtual padding for elements scrolled out of view
            Rectangle {
                height: list-padding-top;
            }

            for item[index] in items: ItemView {
                item: item;
                has-cursor: index + offset == cursor;
            }

            // Virtual padding for remaining elements not yet scrolled into view
            Rectangle {
                height: remaining * Config.item-total-height;
            }
        }

        // Selection rectangle
        Rectangle {
            visible: selecting;

            border-color: green;
            border-width: 2px;
            border-radius: 5px;

            x: Math.min(anchor.x, mouse.x);
            y: Math.min(anchor.y, mouse.y);

            width: Math.abs(mouse.x - anchor.x);
            height: Math.abs(mouse.y - anchor.y);
        }
    }
}
