import { Item, ItemView, ItemKey } from "./items.slint";
import { ScrollView } from "std-widgets.slint";
import { Config } from "config.slint";

export component LazyList {
    in property <[Item]> items;
    in property <int> remaining: 0; // remaining entries to be padded with placeholders for accurate scrollbar size
    callback refresh-entries(offset: int, limit: int);
    callback open(key: ItemKey);

    property <int> offset: Math.floor(-scroll.viewport-y / 110px); // entries hidden by the current scroll offset
    property <int> limit: Math.ceil(scroll.visible-height / 110px); // amount of visible entries
    property <{ x: length, y: length}> select;
    property <bool> selecting: false;

    property <length> list-padding-top;
    property <length> list-padding-bot;

    // Refresh both entries and top padding rectangle at the same time
    // in order to avoid flickering when scrolling at high speed
    function refresh() {
        refresh-entries(offset, limit);
        list-padding-top = offset * 110px;
    }

    changed offset => refresh();
    changed limit => refresh();

    // Reset scroll (call this after navigating)
    public function reset-scroll() {
        scroll.viewport-y = 0;
    }

    // Scroll on select when the cursor is near the top / bottom
    timer := Timer {
        interval: Config.scroll-tick;
        running: selecting;
        triggered() => {
            let range = Config.scroll-range;
            let top = scroll.y - scroll.viewport-y + range;
            let bottom = scroll.y + scroll.visible-height - scroll.viewport-y - range;

            // Check proximity to bottom
            if ta.mouse-y > bottom {
                let speed = min((ta.mouse-y - bottom) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                scroll.viewport-y -= delta;
            // Check proximity to top
            } else if ta.mouse-y < top {
                let speed = min((top - ta.mouse-y) / range, 1);
                let delta = speed * speed * Config.scroll-max-delta;
                scroll.viewport-y += min(delta, -scroll.viewport-y);
            }
        }
    }

    scroll := ScrollView {
        ta := TouchArea {
            pointer-event(event) => {
                if event.kind == PointerEventKind.down {
                    selecting = true;
                    select = { x: ta.mouse-x, y: ta.mouse-y };
                } else if event.kind == PointerEventKind.up {
                    selecting = false;
                } else if event.kind == PointerEventKind.move && selecting {
                    // TODO: collision check for selection
                }
            }
        }

        VerticalLayout {
            spacing: 10px;

            // Virtual padding for elements scrolled out of view
            Rectangle {
                height: list-padding-top;
            }

            for item[index] in items: ItemView {
                item: item;
                open(key) => open(key);
            }

            // Virtual padding for remaining elements not yet scrolled into view
            Rectangle {
                height: remaining * 110px;
            }
        }

        // Selection rectangle
        Rectangle {
            visible: selecting;

            border-color: green;
            border-width: 2px;
            border-radius: 5px;

            x: Math.min(select.x, ta.mouse-x);
            y: Math.min(select.y, ta.mouse-y);

            width: Math.abs(ta.mouse-x - select.x);
            height: Math.abs(ta.mouse-y - select.y);
        }
    }
}
